// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm74xZim6kLGIgDQkMh2FypzOhjqoq-OE',
    appId: '1:123773528987:web:12dd732a187b3920ac0f3e',
    messagingSenderId: '123773528987',
    projectId: 'rider-9bebf',
    authDomain: 'rider-9bebf.firebaseapp.com',
    storageBucket: 'rider-9bebf.appspot.com',
    measurementId: 'G-PE242PH1M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBON8bMPqKnaKYijUn0DuAoJ8dx8fICOrM',
    appId: '1:123773528987:android:6c46af1237f16e95ac0f3e',
    messagingSenderId: '123773528987',
    projectId: 'rider-9bebf',
    storageBucket: 'rider-9bebf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNyYwtdvX1ijDzyNfvft0gE-WZEXdsHxM',
    appId: '1:123773528987:ios:a1b3123941e41159ac0f3e',
    messagingSenderId: '123773528987',
    projectId: 'rider-9bebf',
    storageBucket: 'rider-9bebf.appspot.com',
    iosClientId: '123773528987-gc0jab25nr8ro1fmbufsd54g8a50k9vs.apps.googleusercontent.com',
    iosBundleId: 'com.haiia.rider.gtcRider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNyYwtdvX1ijDzyNfvft0gE-WZEXdsHxM',
    appId: '1:123773528987:ios:a1b3123941e41159ac0f3e',
    messagingSenderId: '123773528987',
    projectId: 'rider-9bebf',
    storageBucket: 'rider-9bebf.appspot.com',
    iosClientId: '123773528987-gc0jab25nr8ro1fmbufsd54g8a50k9vs.apps.googleusercontent.com',
    iosBundleId: 'com.haiia.rider.gtcRider',
  );
}
