Map<String, String> ar = {
  'home_page': 'الصفحة الرئيسية',
  'Select_language': 'اختر اللغة',
  'arbic': 'عربي',
  'login': 'تسجيل دخول',
  'daddyEat': 'أبي',
  'ready_to_go': 'هل أنت مستعد للذهاب؟',
  'signin_now': 'قم بتسجيل دخولك الآن',
  'iD_Number': 'ID Number',
  'password': 'كلمة المرور',
  'remember_me': 'تذكرني',
  'Login': 'الدخول',
  'signin': 'تسجيل الدخول',
  'forgot_password':'هل نسيت كلمة السر؟',
  'click_here':'انقر هنا',
};
