// ignore_for_file: equal_keys_in_map

Map<String, String> en = {
  'home_page': 'Home Page',
  'Select_language': 'Select a language',
  'english': 'English',
  'login': 'login',
  'daddyEat': 'daddyEat',
  'ready_to_go': 'Are you ready to go?',
  'signin_now': 'signin now',
  'iD_Number': 'ID Number',
  'password': 'Password',
  'remember_me': 'Remember me',
  'Login': 'Login',
  'signin': 'signin',
  'order_today': 'Order Today',
  'trip_total': 'Trip Total',
  'planner': 'Planner',
  'earnings': 'Earnings',
  'referrals': 'Referrals',
  'statistics': 'Statistics',
  'inbox': 'Inbox',
  'setting': 'Setting',
  'faqs': 'FAQs',
  'logout': 'Logout',
  'forgot_password': 'forgot password?',
  'click_here': 'Click here',
};
